name: Website Screenshots
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  screenshot:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    environment: env
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Screenshot Script
        env: 
          LOGIN_EMAIL: ${{ secrets.LOGIN_EMAIL }}
          LOGIN_PASSWORD: ${{ secrets.LOGIN_PASSWORD }}
        run: node screenshot.js

      - name: Upload Screenshots
        uses: actions/upload-artifact@v4
        with:
          name: website-screenshots
          path: screenshot-*.png
